//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS_Module
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABIS_ModuleDBEntities : DbContext
    {
        private static ABIS_ModuleDBEntities _context;
        public static ABIS_ModuleDBEntities GetContext()
        {
            if( _context == null) 
                _context = new ABIS_ModuleDBEntities();
            return _context;
        }
        public ABIS_ModuleDBEntities()
            : base("name=ABIS_ModuleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<AdultUsers> AdultUsers { get; set; }
        public virtual DbSet<KidsLibrary> KidsLibrary { get; set; }
        public virtual DbSet<KidsUsers> KidsUsers { get; set; }
        public virtual DbSet<MainLibrary> MainLibrary { get; set; }
    }
}
