//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdultUsers
    {
        public int UserID { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string TakenBooks { get; set; }
    }
}
