//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class KidsLibrary
    {
        public int Id { get; set; }
        public string FIO_Author { get; set; }
        public string Title { get; set; }
        public string TitleType { get; set; }
        public string Year { get; set; }
        public string SerialNumber { get; set; }
        public int IsAvalible { get; set; }
    }
}
